# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yaml and/or the recipe/meta.yaml.

language: objective-c

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=34
    - CONDA_PY=35
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "XNVvvxqE0tNR2GjGyD7aLjBwf7WOvWDCJNeUWxwc0SpINRzCshhBs44H1pia71F9udPWDzdFNJ9NO4TmgbCtBvUxBt7QTuopj50jYqXVxf9Uo4CICZyvK2gNH+jk2/reVgjfr0dDSxd8ED8R9gLT40/F+VIeW1OxRk1j/u0D0dQ4lwo6vFWFX510nOL4ql3XIeoFvkxGMDh3PiX04yM6zIMbJMsGwvg5awxW0LPMGl4kGZ7SAkMHHiGi24f+EqFdL2PYHP8p/hAnpL+7GaA7y0I8YCWnyYKOAnvMx8QNrBjsXMQgRBDaU8XKB0eIVo98xWP5Y1Wk0U9F1AjCo8eit9TADsSsvtWXTDRMXvw0ykZjJHaIolMwAQa5OeACxwBH7PMkxTEy2veyP8kR/U+21Zup+wbWNlbDplM+j6a+fUYtYJugmsLpdJ+5koKMX1FhfypDNN/L7c4GlRwd4uJwm3/8HkjgJ5rta9QwhSV6VKUJQKVmYHJaP8AjWxXFJZgabP4BhbZl5+a6ydINb0gkru6SwoZJcnOGMg1fuTHGp90PLf08HaA9t3s0M9ACwvor/U1oXUAynJWgQbVmoJbVWutmhknIq1RBGAKCRhMYoKRCIsxj6sIxNGqT6jBqRiL/IQPN8h3BXt0NrnUYbLFc5Tr3zJzPlBOUZZEC5ILtkBM="


before_install:
    - brew remove --force $(brew list)

install:
    - |
      MINICONDA_URL="http://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

      export PATH=/Users/travis/miniconda3/bin:$PATH

      conda update --yes conda
      conda install --yes conda-build jinja2 anaconda-client
      conda config --add channels conda-forge
      

script:
  - conda build ./recipe

after_success:

  - ./ci_support/upload_or_check_non_existence.py ./recipe conda-forge --channel=main
