travis:
  secure:
    BINSTAR_TOKEN: XNVvvxqE0tNR2GjGyD7aLjBwf7WOvWDCJNeUWxwc0SpINRzCshhBs44H1pia71F9udPWDzdFNJ9NO4TmgbCtBvUxBt7QTuopj50jYqXVxf9Uo4CICZyvK2gNH+jk2/reVgjfr0dDSxd8ED8R9gLT40/F+VIeW1OxRk1j/u0D0dQ4lwo6vFWFX510nOL4ql3XIeoFvkxGMDh3PiX04yM6zIMbJMsGwvg5awxW0LPMGl4kGZ7SAkMHHiGi24f+EqFdL2PYHP8p/hAnpL+7GaA7y0I8YCWnyYKOAnvMx8QNrBjsXMQgRBDaU8XKB0eIVo98xWP5Y1Wk0U9F1AjCo8eit9TADsSsvtWXTDRMXvw0ykZjJHaIolMwAQa5OeACxwBH7PMkxTEy2veyP8kR/U+21Zup+wbWNlbDplM+j6a+fUYtYJugmsLpdJ+5koKMX1FhfypDNN/L7c4GlRwd4uJwm3/8HkjgJ5rta9QwhSV6VKUJQKVmYHJaP8AjWxXFJZgabP4BhbZl5+a6ydINb0gkru6SwoZJcnOGMg1fuTHGp90PLf08HaA9t3s0M9ACwvor/U1oXUAynJWgQbVmoJbVWutmhknIq1RBGAKCRhMYoKRCIsxj6sIxNGqT6jBqRiL/IQPN8h3BXt0NrnUYbLFc5Tr3zJzPlBOUZZEC5ILtkBM=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
